sass:
  sass_dir: _sass

name: 'squiggly lines'
title: 'squiggly lines'
tagline: 'perfectly imperfect'
author: 'slesa'
company: '@saanostory ink.'
repository: slesaad/squiggly-lines

instagram: 'https://www.instagram.com/saanostory/'
github: 'https://github.com/slesaad/'
email: 'mailto:slesaad@gmail.com'
website: 'https://slesa.com.np'
linkedin: 'https://linkedin.com/in/slesaad'

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 8
  permalink: '/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
