sass:
  sass_dir: _sass

name: 'squiggly lines'
title: 'squiggly lines'
tagline: 'perfectly imperfect'
author: 'slesa'
company: '@saanostory ink.'

instagram: 'https://www.instagram.com/saanostory/'
github: 'https://github.com/slesaad/'
email: 'mailto:slesaad@gmail.com'
website: 'https://slesa.com.np'
linkedin: 'https://linkedin.com/in/slesaad'

paginate: 3
paginate_path: "/blog/page:num/"
