version: '3.3'
services:
  jekyll:
    ports:
      - 35729:35729
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    image: jekyll/jekyll
    command: jekyll serve --incremental --livereload --force_polling
